@RushDay_HostAddress = http://localhost:5080

### JSON index
GET {{RushDay_HostAddress}}/api

### Health
GET {{RushDay_HostAddress}}/health

### A results-day dashboard
GET {{RushDay_HostAddress}}/students/S000001/dashboard
Accept: application/json

### Module catalogue
GET {{RushDay_HostAddress}}/modules
Accept: application/json

### The oversubscribed elective
GET {{RushDay_HostAddress}}/modules/CS3099
Accept: application/json

### Enrol on it
POST {{RushDay_HostAddress}}/students/S000001/enrolments
Content-Type: application/json

{
  "moduleCode": "CS3099"
}
