/**
 * `GET /data/load-results.json` (05-frontend.md section 8): a static file generated by
 * `load/summarize.mjs` from `load/results/*.json` and `load/results/runs.json`, served from
 * `public/data/` and committed. Read by `/story` (public) and the "load story" section of
 * `/admin/ops`. Until v1 runs are committed every run has `version: 'v0'` and the charts render the
 * "after" series as "not yet measured".
 */

export type LoadScenario = 'enrolment-rush' | 'results-day' | 'dashboard-knee' | 'login-storm'
export type LoadVersion = 'v0' | 'v1'

export interface LoadRunMetrics {
  requests: number
  failedRate: number
  p50Ms: number
  p95Ms: number
  /** Optional for every run: only the runs whose k6 script set `summaryTrendStats` to include p(99). */
  p99Ms?: number
  maxMs: number
  achievedRate?: number
  droppedIterations?: number
  accepted?: number
  rejectedFull?: number
  rejectedOther?: number
  shed?: number
  errored?: number
  /** The module's capacity at the time of the run (business fact, not a k6 metric); enables `oversold`. */
  capacity?: number
  /** `max(0, accepted - capacity)`: places handed out beyond capacity. */
  oversold?: number
  loginsOk?: number
  loginsRateLimited?: number
}

export interface LoadRun {
  id: string
  scenario: LoadScenario
  version: LoadVersion
  label: string
  ranAt: string
  /** Path to the raw k6 JSON summary, relative to the repository root ("Raw test output" link). */
  source: string
  targetRate?: number
  mode?: 'guard' | 'spray'
  notes?: string
  metrics: LoadRunMetrics
}

export interface LoadResults {
  generatedAt: string
  /** A description of the machine the runs happened on, for the honesty banner (never a hostname). */
  machine: string
  runs: LoadRun[]
}
